### ISSUE TITLE
Mismatched versions in specification files

### ISSUE THREAD

**Issue by FabijanC** [starkware-libs/starknet-specs#181]
As of spec version v0.6.0-rc5, while [api/starknet_api_openrpc.json](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0-rc5/api/starknet_api_openrpc.json#L4) has `version: 0.6.0`, the [write](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0-rc5/api/starknet_write_api.json#L4) and [trace](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0-rc5/api/starknet_trace_api_openrpc.json#L4) files have `0.5.0`.

Is this on purpose? Should the versioning of every file really be independent? I feel like something is wrong because in v0.5.1, the version in all three files was indeed `0.5.1`.

If this really is a mistake, a good idea would be to improve the validation workflow this repository uses (namely `validate.js`). Perhaps it could use the `version` property in `package.json` as the source of truth, and check all the spec files against that. I'd be willing to make a contribution.

**Comment by Mirko-von-Leipzig** [comment]
Fairly sure it's not on purpose. I think go ahead with adding the CI check; always nice to not worry about it.
