### ISSUE TITLE
Extra fields returned by nodes when executing transactions

### ISSUE THREAD

**Issue by franciszekjob** [starkware-libs/starknet-specs#226]
Some extra fields are returned in the result when executing transaction, i.e. performing `starknet_add<type>Transaction` call. 
e.g.:
- `transaction_hash` field is returned alongside every type of transaction
- `contract_address` field is returned alongisde deploy account transaction

This happens with devnet and juno nodes. Is there a known reason for this disparity or it's just the behavior of nodes?

**Comment by ArielElp** [comment]
This appears consistent with the [specs](https://github.com/starkware-libs/starknet-specs/blob/b69b972bf9ce9e78ef1b6cf064c236e15e25045c/api/starknet_write_api.json#L161), so I'm not sure what's the issue
